dist: precise
sudo: false

language:
    - php
    - node_js

php:
    - 5.3

env:
    - WP_VERSION=latest WP_MULTISITE=0

install:
    - nvm install 4 && nvm use 4
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh
